#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

DEVICE_ID="${MEDIA_SFU_IOS_DEVICE_ID:-}"       # Required: export MEDIA_SFU_IOS_DEVICE_ID=<your device UDID>
DEVICECTL_ID="${MEDIA_SFU_IOS_DEVICECTL_ID:-}" # Required: export MEDIA_SFU_IOS_DEVICECTL_ID=<your devicectl UUID>
API_USERNAME="${MEDIASFU_API_USERNAME:-}"       # Required: export MEDIASFU_API_USERNAME before running
CREDS_FILE="${MEDIASFU_CREDS_FILE:-/tmp/mediasfu_creds.txt}"
RUN_ID_PREFIX="${MEDIASFU_FULL_MATRIX_RUN_ID_PREFIX:-iosmatrix$(date +%Y%m%d%H%M%S)}"

if [[ -z "${MEDIASFU_API_KEY:-}" && ! -f "$CREDS_FILE" ]]; then
  echo "MEDIASFU_API_KEY is required, either exported or available in $CREDS_FILE." >&2
  exit 2
fi

run_stage() {
  local stage_name="$1"
  shift

  echo "== Running iOS physical media matrix stage: $stage_name =="
  env \
    MEDIA_SFU_IOS_DEVICE_ID="$DEVICE_ID" \
    MEDIA_SFU_IOS_DEVICECTL_ID="$DEVICECTL_ID" \
    MEDIASFU_API_USERNAME="$API_USERNAME" \
    MEDIA_SFU_ENABLE_IOS_NATIVE_BRIDGE_PACKAGE="${MEDIA_SFU_ENABLE_IOS_NATIVE_BRIDGE_PACKAGE:-1}" \
    MEDIA_SFU_ENABLE_REAL_LIBMEDIASOUPCLIENT_BINDING="${MEDIA_SFU_ENABLE_REAL_LIBMEDIASOUPCLIENT_BINDING:-1}" \
    MEDIASFU_REQUIRE_REAL_NATIVE_BRIDGE="${MEDIASFU_REQUIRE_REAL_NATIVE_BRIDGE:-1}" \
    MEDIASFU_USE_INSTALLED_APP="${MEDIASFU_USE_INSTALLED_APP:-1}" \
    MEDIASFU_FAIL_ON_OPTIONAL_PROBE_FAILURE=1 \
    MEDIASFU_PROBE_RUN_ID="${RUN_ID_PREFIX}_${stage_name}" \
    "$@" \
    ./scripts/run_ios_physical_media_probe.sh
}

run_stage browserprejoin \
  MEDIASFU_RUN_EXISTING_MEDIA_PROBE=1 \
  MEDIASFU_EXISTING_AUDIO_EXPECT_SUBSTRING=audioResumes=1 \
  MEDIASFU_EXISTING_VIDEO_EXPECT_SUBSTRING=videoMatches=1 \
  MEDIASFU_RUN_SCREENSHARE_PROBE=1 \
  MEDIASFU_SCREENSHARE_SOURCE=browser \
  MEDIASFU_BROWSER_SCREENSHARE_TIMING=prejoin \
  MEDIASFU_SCREENSHARE_EXPECT_SUBSTRING=remoteScreenShare=true \
  MEDIASFU_SCREENSHARE_MIN_ACTIVE_VIDEOS="${MEDIASFU_BROWSER_PREJOIN_SCREENSHARE_MIN_ACTIVE_VIDEOS:-3}"

run_stage iosshare \
  MEDIASFU_RUN_SCREENSHARE_PROBE=1 \
  MEDIASFU_SCREENSHARE_SOURCE=ios \
  MEDIASFU_SCREENSHARE_EXPECT_SUBSTRING=appDataMediaTag=screen-video \
  MEDIASFU_SCREENSHARE_MIN_ACTIVE_VIDEOS="${MEDIASFU_IOS_SCREENSHARE_MIN_ACTIVE_VIDEOS:-2}"

echo "iOS physical media matrix completed for run prefix=$RUN_ID_PREFIX."